# assets.py - Updated with actual Quotex asset names

# Live market assets (using actual Quotex naming)
live_assets = [
    "AUD/CAD",
    "AUD/CHF", 
    "AUD/JPY",
    "AUD/USD",
    "CAD/CHF",
    "CAD/JPY",
    "CHF/JPY",
    "EUR/AUD",
    "EUR/CAD",
    "EUR/CHF",
    "EUR/GBP",
    "EUR/JPY",
    "EUR/NZD",
    "EUR/USD",
    "GBP/AUD",
    "GBP/CAD",
    "GBP/CHF",
    "GBP/JPY",
    "GBP/NZD",
    "GBP/USD",
    "NZD/CAD",
    "NZD/CHF",
    "NZD/JPY",
    "NZD/USD",
    "USD/CAD",
    "USD/CHF",
    "USD/JPY"
]

# OTC market assets (using actual Quotex naming)
otc_assets = [
    "AUD/CAD (OTC)",
    "AUD/CHF (OTC)",
    "AUD/JPY (OTC)",
    "AUD/NZD (OTC)",
    "AUD/USD (OTC)",
    "CAD/CHF (OTC)",
    "CAD/JPY (OTC)",
    "CHF/JPY (OTC)",
    "EUR/AUD (OTC)",
    "EUR/CAD (OTC)",
    "EUR/CHF (OTC)",
    "EUR/GBP (OTC)",
    "EUR/JPY (OTC)",
    "EUR/NZD (OTC)",
    "EUR/USD (OTC)",
    "GBP/AUD (OTC)",
    "GBP/CAD (OTC)",
    "GBP/CHF (OTC)",
    "GBP/JPY (OTC)",
    "GBP/NZD (OTC)",
    "GBP/USD (OTC)",
    "NZD/CAD (OTC)",
    "NZD/CHF (OTC)",
    "NZD/JPY (OTC)",
    "NZD/USD (OTC)",
    "USD/CAD (OTC)",
    "USD/CHF (OTC)",
    "USD/JPY (OTC)"
]
